const initialState = {
  deviceType: '',
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2014/07/10/17/17/bedroom-389254_1280.jpg',
      favorite: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2020/11/24/11/36/bedroom-5772286_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2016/12/30/07/55/bedroom-1940169_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2018/10/28/12/37/bedroom-3778695_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2018/07/14/17/19/interior-3538020_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2017/04/28/22/16/room-2269594_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://cdn.pixabay.com/photo/2014/08/11/21/31/wall-panel-416041_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: 'https://cdn.pixabay.com/photo/2018/09/24/15/02/bed-3700115_1280.jpg',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3659681/pexels-photo-3659681.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1329711/pexels-photo-1329711.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3773581/pexels-photo-3773581.png?auto=compress&cs=tinysrgb&h=750&w=1260',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3773575/pexels-photo-3773575.png?auto=compress&cs=tinysrgb&h=750&w=1260',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/6198658/pexels-photo-6198658.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3753435/pexels-photo-3753435.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1050&q=80',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/photo-1566665797739-1674de7a421a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/photo-1592229505678-cf99a9908e03?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/photo-1571508601936-6ca847b47ae4?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1051&q=80',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/photo-1572297258415-b9cc3cc5bb71?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1051&q=80',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/photo-1574873215043-44119461cb3b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/flagged/photo-1573168710865-2e4c680d921a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1050&q=80',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/photo-1588046130717-0eb0c9a3ba15?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=719&q=80',
      favorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.unsplash.com/flagged/photo-1556438758-8d49568ce18e?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1053&q=80',
      favorite: false,
      compare: false,
    },
  ],
  brands: [
    {
      id: 'brand-1',
      image:
        'https://cdn.pixabay.com/photo/2015/05/04/20/23/corporate-752923_960_720.png',
    },
    {
      id: 'brand-2',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/color-752920_960_720.png',
    },
    {
      id: 'brand-3',
      image: 'https://cdn.pixabay.com/photo/2015/05/03/12/38/logo-751133_960_720.png',
    },
    {
      id: 'brand-4',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752922_960_720.png',
    },
    {
      id: 'brand-5',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-6',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-7',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-8',
      image:
        'https://cdn.pixabay.com/photo/2015/05/04/20/23/corporate-752923_960_720.png',
    },
    {
      id: 'brand-9',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-10',
      image:
        'https://cdn.pixabay.com/photo/2015/05/04/20/23/corporate-752923_960_720.png',
    },
    {
      id: 'brand-11',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-12',
      image:
        'https://cdn.pixabay.com/photo/2015/05/04/20/23/corporate-752923_960_720.png',
    },
    {
      id: 'brand-13',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-14',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-15',
      image:
        'https://cdn.pixabay.com/photo/2015/05/04/20/23/corporate-752923_960_720.png',
    },
    {
      id: 'brand-16',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-17',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-18',
      image:
        'https://cdn.pixabay.com/photo/2015/05/04/20/23/corporate-752923_960_720.png',
    },
    {
      id: 'brand-19',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-20',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-21',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'brand-22',
      image:
        'https://cdn.pixabay.com/photo/2015/05/04/20/23/corporate-752923_960_720.png',
    },
    {
      id: 'brand-23',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/color-752920_960_720.png',
    },
    {
      id: 'brand-24',
      image: 'https://cdn.pixabay.com/photo/2015/05/04/20/23/logo-752921_960_720.png',
    },
    {
      id: 'mauris-eu-nunc-1',
      name: 'Mauris eu nunc 1',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-2',
      name: 'Mauris eu nunc 2',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-3',
      name: 'Mauris eu nunc 3',
      category: 'chair',
      price: 20,
      oldPrice: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-4',
      name: 'Mauris eu nunc 4',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-5',
      name: 'Mauris eu nunc 5',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-6',
      name: 'Mauris eu nunc 6',
      category: 'chair',
      price: 20,
      oldPrice: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-7',
      name: 'Mauris eu nunc 7',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-8',
      name: 'Mauris eu nunc 8',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-9',
      name: 'Mauris eu nunc 9',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-10',
      name: 'Mauris eu nunc 10',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-11',
      name: 'Mauris eu nunc 11',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-12',
      name: 'Mauris eu nunc 12',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-13',
      name: 'Mauris eu nunc 13',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-14',
      name: 'Mauris eu nunc 14',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-15',
      name: 'Mauris eu nunc 15',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-16',
      name: 'Mauris eu nunc 16',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-17',
      name: 'Mauris eu nunc 17',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-18',
      name: 'Mauris eu nunc 18',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-19',
      name: 'Mauris eu nunc 19',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'mauris-eu-nunc-20',
      name: 'Mauris eu nunc 20',
      category: 'chair',
      price: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-1',
      name: 'Etiam molestie magna 1',
      category: 'sofa',
      price: 35,
      oldPrice: 49,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-2',
      name: 'Etiam molestie magna 2',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-3',
      name: 'Etiam molestie magna 3',
      category: 'sofa',
      price: 35,
      oldPrice: 49,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-4',
      name: 'Etiam molestie magna 4',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-5',
      name: 'Etiam molestie magna 5',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-6',
      name: 'Etiam molestie magna 6',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-7',
      name: 'Etiam molestie magna 7',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-8',
      name: 'Etiam molestie magna 8',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-9',
      name: 'Etiam molestie magna 9',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-10',
      name: 'Etiam molestie magna 10',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-11',
      name: 'Etiam molestie magna 11',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-12',
      name: 'Etiam molestie magna 12',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-13',
      name: 'Etiam molestie magna 13',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-14',
      name: 'Etiam molestie magna 14',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-15',
      name: 'Etiam molestie magna 15',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-16',
      name: 'Etiam molestie magna 16',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-17',
      name: 'Etiam molestie magna 17',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'etiam-molestie-magna-18',
      name: 'Etiam molestie magna 18',
      category: 'sofa',
      price: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-1',
      name: 'In egestas sem 1',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-2',
      name: 'In egestas sem 2',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-3',
      name: 'In egestas sem 3',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-4',
      name: 'In egestas sem 4',
      category: 'table',
      price: 29,
      oldPrice: 49,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-5',
      name: 'In egestas sem 5',
      category: 'table',
      price: 29,
      oldPrice: 49,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-6',
      name: 'In egestas sem 6',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-7',
      name: 'In egestas sem 7',
      category: 'table',
      price: 29,
      oldPrice: 49,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-8',
      name: 'In egestas sem 8',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-9',
      name: 'In egestas sem 9',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-10',
      name: 'In egestas sem 10',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-11',
      name: 'In egestas sem 11',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-12',
      name: 'In egestas sem 12',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-13',
      name: 'In egestas sem 13',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-14',
      name: 'In egestas sem 14',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-15',
      name: 'In egestas sem 15',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-16',
      name: 'In egestas sem 16',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-17',
      name: 'In egestas sem 17',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-18',
      name: 'In egestas sem 18',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-19',
      name: 'In egestas sem 19',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-20',
      name: 'In egestas sem 20',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-21',
      name: 'In egestas sem 21',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-22',
      name: 'In egestas sem 22',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-23',
      name: 'In egestas sem 23',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-24',
      name: 'In egestas sem 24',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-25',
      name: 'In egestas sem 25',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-26',
      name: 'In egestas sem 26',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-27',
      name: 'In egestas sem 27',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-28',
      name: 'In egestas sem 28',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-29',
      name: 'In egestas sem 29',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'in-egestas-sem-30',
      name: 'In egestas sem 30',
      category: 'table',
      price: 29,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-1',
      name: 'Pellentesque id dolor 1',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-2',
      name: 'Pellentesque id dolor 2',
      category: 'dining',
      price: 33,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-3',
      name: 'Pellentesque id dolor 3',
      category: 'dining',
      price: 33,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-4',
      name: 'Pellentesque id dolor 4',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-5',
      name: 'Pellentesque id dolor 5',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-6',
      name: 'Pellentesque id dolor 6',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-7',
      name: 'Pellentesque id dolor 7',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-8',
      name: 'Pellentesque id dolor 8',
      category: 'dining',
      price: 33,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-9',
      name: 'Pellentesque id dolor 9',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-10',
      name: 'Pellentesque id dolor 10',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-11',
      name: 'Pellentesque id dolor 11',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-12',
      name: 'Pellentesque id dolor 12',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-13',
      name: 'Pellentesque id dolor 13',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-14',
      name: 'Pellentesque id dolor 14',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-15',
      name: 'Pellentesque id dolor 15',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-16',
      name: 'Pellentesque id dolor 16',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
    {
      id: 'pellentesque-id-dolor-17',
      name: 'Pellentesque id dolor 17',
      category: 'dining',
      price: 33,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
    },
  ],
  feedbacks: [
    {
      id: 1,
      quote:
        'Curabitur gravida dictum pulvinar. Aenean scelerisque sem eu imperdiet cursus. Cras porttitor elit imperdiet congue dignissim. Duis vitae nulla vitae risus lobortis tincidunt. Proin lacus turpis, volutpat eget sodales eu, vestibulum quis leo.',
      image:
        'https://images.pexels.com/photos/7219665/pexels-photo-7219665.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      name: '~ John Smith',
    },
    {
      id: 2,
      quote:
        'Curabitur gravida dictum pulvinar. Aenean scelerisque sem eu imperdiet cursus. Cras porttitor elit imperdiet congue dignissim. Duis vitae nulla vitae risus lobortis tincidunt. Proin lacus turpis, volutpat eget sodales eu, vestibulum quis leo.',
      image:
        'https://images.pexels.com/photos/3770254/pexels-photo-3770254.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      name: '~ Clara Oswald',
    },
    {
      id: 3,
      quote:
        'Curabitur gravida dictum pulvinar. Aenean scelerisque sem eu imperdiet cursus. Cras porttitor elit imperdiet congue dignissim. Duis vitae nulla vitae risus lobortis tincidunt. Proin lacus turpis, volutpat eget sodales eu, vestibulum quis leo.',
      image:
        'https://images.pexels.com/photos/4946649/pexels-photo-4946649.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      name: '~ Meredith Grey',
    },
  ],
  cart: {
    products: [],
  },
  deals: {
    leftImage:
      'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    leftDescription: ['Guest room', 'Chairs', '-20%'],
    rightUpImage:
      'https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?cs=srgb&fm=jpg&h=750&w=1260',
    rightUpDescription: ['Bed', 'room', 'Collection', '$200.00'],
    rightDownImage:
      'https://images.pexels.com/photos/2631746/pexels-photo-2631746.jpeg?cs=srgb&fm=jpg&h=750&w=1260',
    rightDownDescription: [
      'Special',
      ' collection',
      'Save up ',
      '45%',
      ' of furniture',
    ],
  },
  promotion: {
    picture:
      'https://images.pexels.com/photos/276534/pexels-photo-276534.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    picture2:
      'https://images.pexels.com/photos/276528/pexels-photo-276528.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
};

export default initialState;
